# -*- coding: utf-8 -*-
"""model_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FxnmrvRBMsYfshC5-Hnz7G_S7ZPyTUu
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os

zip_path = "/content/drive/MyDrive/dataset.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/")

print("Extraction Done")
print(os.listdir("/content/"))

print(os.listdir("/content/dataset"))

import os

print("Main folders:", os.listdir("/content/dataset"))
print("Train classes:", os.listdir("/content/dataset/train"))
print("Val classes:", os.listdir("/content/dataset/validate"))
print("Test classes:", os.listdir("/content/dataset/test"))

import tensorflow as tf
print("GPU Available:", tf.config.list_physical_devices('GPU'))

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.metrics import classification_report, confusion_matrix
import os

TRAIN_DIR = "/content/dataset/train"
VAL_DIR   = "/content/dataset/validate"
TEST_DIR  = "/content/dataset/test"

print("Train classes:", os.listdir(TRAIN_DIR))

# 5️⃣ Config
# =========================
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 6

# =========================
# 6️⃣ Data Generators
# =========================
train_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True
)

val_test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

val_gen = val_test_datagen.flow_from_directory(
    VAL_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_gen = val_test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False
)

print("Train samples:", len(train_gen.filenames))
print("Validation samples:", len(val_gen.filenames))
print("Test samples:", len(test_gen.filenames))

# 7️⃣ Model (V1 Architecture)
# =========================
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),

    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# 8️⃣ Callbacks
# =========================
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

checkpoint = ModelCheckpoint(
    "/content/drive/MyDrive/ai_image_detector_large_gpu.h5",
    save_best_only=True,
    monitor='val_loss'
)

# =========================
# 9️⃣ Train
# =========================
history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS,
    callbacks=[early_stop, checkpoint]
)

# 🔟 Plot Accuracy
# =========================
plt.figure(figsize=(8,4))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.legend()
plt.title("Training vs Validation Accuracy")
plt.show()

# =========================
# 1️⃣1️⃣ Test Evaluation
# =========================
preds = (model.predict(test_gen) > 0.5).astype("int32")

print("\n=== TEST RESULTS ===")
print(classification_report(test_gen.classes, preds))

cm = confusion_matrix(test_gen.classes, preds)

plt.figure(figsize=(5,5))
plt.imshow(cm, cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.colorbar()
plt.show()

print("✅ Model saved ")

import tensorflow as tf
print(tf.__version__)

#2

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.metrics import classification_report, confusion_matrix
import os

TRAIN_DIR = "/content/dataset/train"
VAL_DIR   = "/content/dataset/validate"
TEST_DIR  = "/content/dataset/test"

IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 6

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    horizontal_flip=True
)

val_test_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

train_gen = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

val_gen = val_test_datagen.flow_from_directory(
    VAL_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_gen = val_test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False
)

base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(224,224,3)
)

# Freeze base model
base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation="relu")(x)
x = Dropout(0.5)(x)
output = Dense(1, activation="sigmoid")(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=2,
    restore_best_weights=True
)

checkpoint = ModelCheckpoint(
    "/content/drive/MyDrive/ai_image_detector_mobilenet.h5",
    save_best_only=True,
    monitor="val_loss"
)

history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS,
    callbacks=[early_stop, checkpoint]
)

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.legend()
plt.title("Training vs Validation Accuracy")
plt.show()

preds = (model.predict(test_gen) > 0.5).astype("int32")

print("\n=== TEST RESULTS ===")
print(classification_report(test_gen.classes, preds))

cm = confusion_matrix(test_gen.classes, preds)

plt.imshow(cm, cmap="Blues")
plt.title("Confusion Matrix")
plt.colorbar()
plt.show()